server:
  servlet:
    context-path: /e-commerce-be/api

  springdoc:
    swagger-ui:
      path: /public/swagger

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
